### ISSUE TITLE
Model inside a model support in response definition

### ISSUE THREAD

**Issue by tecnom1k3** [vanderlee/PHPSwaggerGen#10]
I have the following model definitions:

```
/**
 * @rest\model address object defining station address.
 * @rest\property string address_line1 address line1
 * @rest\property string address_line2 address line2
 * @rest\property string city city
 * @rest\property string state state
 * @rest\property string postal_code postal code
 * @rest\property string country_code country code
 * @rest\property string phone phone
 * @rest\property string fax fax
 *
 * @rest\model stations Returns list of station for a given supplier id.
 * @rest\property int id supplier Id
 * @rest\property int supplier supplier Id
 * @rest\property string name  Supplier Name
 * @rest\property address Address Station Address
 * @rest\property string latitude latitude
 * @rest\property string longitude longitude
 * @rest\property string timezone timezone
 * @rest\property string station_type Station Type
 */
```

and later on declaring the response type as follows:

```
 /** @rest\endpoint /stations/{supplier_id}
     * @rest\method GET Returns list of station for a given supplier id.
     * @rest\response 200 stations
    */
```

so I'm trying to make a reference of a model inside another model.  but when I execute, I get the following exception: `Property format not recognized: 'address'`

is model inside a model supported the same way as an array of models?

if the definition is changed as follows, the generation executes successfuly, but does not match the real output of my API

```
/**
 * @rest\model address object defining station address.
 * @rest\property string address_line1 address line1
 * @rest\property string address_line2 address line2
 * @rest\property string city city
 * @rest\property string state state
 * @rest\property string postal_code postal code
 * @rest\property string country_code country code
 * @rest\property string phone phone
 * @rest\property string fax fax
 *
 * @rest\model stations Returns list of station for a given supplier id.
 * @rest\property int id supplier Id
 * @rest\property int supplier supplier Id
 * @rest\property string name  Supplier Name
 * @rest\property array(address) Address Station Address
 * @rest\property string latitude latitude
 * @rest\property string longitude longitude
 * @rest\property string timezone timezone
 * @rest\property string station_type Station Type
 */
```

thank you

**Comment by vanderlee** [comment]
That's a good idea!

From the top of my head, I don't know if the Swagger/Open-API spec permits this type of referencing. If it does, than implementing it should be easy. If it does not, it could still be implemented but will take a bit more effort.

The current "support" for array references is probably a bug; this was not intentional and has to do with the way SG handles types. Could you describe what you think the result should be and what SG currently generates?

I'll try to find some time this weekend to look into this.

**Comment by tecnom1k3** [comment]
I think Swagger does permit, at least at swagger editor.  Consider the following yaml:

```yaml
swagger: '2.0'
info:
  title: API
  description: Description
  version: "1.0"
host: myhost.com
schemes:
  - https
basePath: /
consumes:
  - application/json
produces:
  - application/json
paths:
  /stations:
    get:
      description: |
        Returns list of station for a given supplier id.
      responses:
        200:
          description: An Object defining response from Station
          schema:
              $ref: '#/definitions/Stations'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  Address:
    description: Object defining Address.
    properties:
      address_line1:
        type: string
      address_line2:
        type: string
      city:
        type: string
      state:
        type: string
      postal_code:
        type: string
      country_code:
        type: string
      phone:
        type: string
      fax:
        type: string
  Stations:
    type: array
    items:
      $ref: '#/definitions/Station'
  Station:
    description: Detailsof station.
    properties:
      id:
        type: integer
      name:
        type: string
      address:
        $ref: '#/definitions/Address'
```

As you can see, the Stations schema contains and array of Station objects (that is why I was expecting that `@rest\property array(address)` to work fine).  At the same time, Station contains a reference to the address object.  This way, editor.swagger.io does not complaints and produces the following output:

![image](https://cloud.githubusercontent.com/assets/1458333/19577622/dcff0f78-96cc-11e6-9568-cf0ec201d208.png)
 
I can get SG to generate an array of referenced objects, but fail to generate a referenced object within another referenced object.  

Hope this helps, please let me know if you need additional information.  I would like to contribute, but at this time I find myself with very limited time :(  I'm also attaching YAML above converted to JSON

Thanks!
[swagger (1).json.zip](https://github.com/vanderlee/PHPSwaggerGen/files/542890/swagger.1.json.zip)

**Comment by vanderlee** [comment]
This was a pretty simple fix, adding some useful functionality.
Thanks for the issue and all the example code, which greatly helped finding and fixing this issue.
Fix and unittest coverage included in 2.3.7
Please let me know if this works for you.

**Comment by tecnom1k3** [comment]
Awesome! 

Will update and test, and will let you know.

**Comment by tecnom1k3** [comment]
Confirming the generated docs work as expected in the swagger editor using version 2.3.7.  Thanks
