### ISSUE TITLE
HEAD operation is not supported

### ISSUE THREAD

**Issue by weirdan** [vanderlee/PHPSwaggerGen#16]
Swagger spec says HEAD method is allowed: https://swagger.io/specification/#fixed-fields-33
However swaggergen does not list it as acceptable: https://github.com/vanderlee/PHPSwaggerGen/blob/55e75e30f846705abf207aa690ef832e1868c367/SwaggerGen/Swagger/Path.php#L17

**Comment by vanderlee** [comment]
I'll add it. I think `OPTIONS` method may be missing too.

**Comment by vanderlee** [comment]
Both issues should be fixed in version 2.3.13 just released

**Comment by weirdan** [comment]
Great, thank you!
