### ISSUE TITLE
@rest/require should create object on each item

### ISSUE THREAD

**Issue by Dezinger** [vanderlee/PHPSwaggerGen#2]
@rest\require auth_token
@rest\require auth_code
@rest\require auth_implicit

it should be:
https://monosnap.com/file/FH4NnOGbsA97CvPPySxWrq8poefiWc.png
http://swagger.io/specification/#securityRequirementObject

but now it is elemet of array:
https://monosnap.com/file/KkSDqHfxflSB9fikwcNn11Ke51oG3e.png

**Comment by vanderlee** [comment]
Thanks for the detailed bug report!
I added new testcases to confirm the fix but could you please verify that the new version (2.0.15) fixes this issue?
