### ISSUE TITLE
Feature request for support example attribute for elements

### ISSUE THREAD

**Issue by oozolii** [vanderlee/PHPSwaggerGen#22]
Dear Developer(s),

I want to ask you to develop PHPSwaggerGen to support example attribute for swagger.
What I mean?

> responses:
        200:
          description: 'Succes data request'
          schema:
            properties:
              code:
                type: string
                example: "SUCCESS"
              message:
                type: string
                example: "Your request was successfully!"

More about this attribute: [https://swagger.io/docs/specification/adding-examples/](url)

Would be nice to have this feature too. Thank you!

**Comment by vanderlee** [comment]
I think that would be quite doable. Will look into it somewhere in the coming weeks.
Do you know if the SwaggerUI can handle examples.

**Comment by oozolii** [comment]
Thank you very much! SwaggerUI can handle examples. 
Check here in the example: 
[http://petstore.swagger.io/?_ga=2.136686704.1540059357.1509039902-598612444.1509039902](url)

And here is the json for that: [http://petstore.swagger.io/v2/swagger.json](url)

The "example" shows up in the UI when you see eg. the "Add a new pet to the store" body options object.

**Comment by vanderlee** [comment]
I've added support for `example` to all types and to the Response context.

Note that PHPSwaggerGen bases off the 2.0 spec. Relevant page on `examples` is here: https://swagger.io/docs/specification/2-0/adding-examples/.

The page you linked to was for OAS3. I may support 3.0 in the future, but currently have no plans to do so.

**Comment by oozolii** [comment]
Thank you very much!
