### ISSUE TITLE
additionalProperties support

### ISSUE THREAD

**Issue by weirdan** [vanderlee/PHPSwaggerGen#30]
I'm going to propose PR for `additionalProperties` object type attribute, and wanted to check with you on the inline definition format I envision:
```
object(type)
object(propName:type,propName2:type,type)
object(type,propName:type,...,type) // errors out with 
                                    // 'duplicate additionalProperties type specified'
{[integer]} // string -> array of int hash
```
The command form would be:
```
additionalproperties type // a bit of a mouthful, 
                          // but close to the spec language on the other hand
```

**Comment by vanderlee** [comment]
I love additionalProperties; they've been on top of my wishlist for a while now.

Just to get a clear idea of what you're trying to do. Would the following parse correctly?
```
object(type,propName:type)
object(propName:type,type,...)
object(propName:type,...)
object(...)
object(type,type)
object(type,...)
object(...,type) // I expect this should error?
```

As for the command form, wouldn't `property type` or `property ...` work, using variants of the current syntax for adding named properties to an object?

**Comment by weirdan** [comment]
* `object(typeA,propName:typeB)` - would be parsed as object with `propName` of `typeB` and any additional properties of `typeA` (could be in any order, so `object(firstName:string,object,lastName:string)` would also be possible, meaning first and last names are strings, and anything else is an object)
* `object(...)` - not sure what you mean here, you seem to imply literal ellipsis has some special meaning, while I was using ellipsis to signify there's some more named props in the example, omitted for brevity
* `object(type,type)` - that would be error, additional properties type defined twice

To give some more concrete examples:
```php
function getCountries(): stdClass {
  $ret = [];
  $ret["count"] = 2;
  $ret["UK"] = "Great Britain";
  $ret["US"] = "The United States";
  return (object) $ret;
}
```
would be documented/annotated to return this: `object(string,count:integer)`, and
```php
function getCustomer($id): CustomerDTO {
   $ret = new CustomerDTO;
   $ret->firstName = "John";
   $ret->lastName = "Doe"
   $ret->counts = (object) [
       "total" => [1,2,3],
       "current" => [2,3,4]
   ];
   return $ret;
}
```
- like this: 
```
model CustomerDTO object(firstName:string,lastName:string,counts:object(array(integer)))
```
> using variants of the current syntax for adding named properties to an object?

Like, the same command but omitting the property name? That could work, but might lead to accidentally omitted prop name definition suddenly becoming the additional properties type definition. I'd prefer a separate command name.

**Comment by weirdan** [comment]
> might lead to accidentally omitted prop name definition suddenly becoming the additional properties type definition. I'd prefer a separate command name.

On the second thought though, it's what I actually propose for inline format, so it might make sense for consistency :smile:

**Comment by weirdan** [comment]
BTW, currently SG does not emit "additionalProperties" constraint for objects, which means any additional properties are valid (`"additionalProperties": true` is implied by the spec, see [p 5.4.4.3](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#page-12)).

So if you thought about `object(...)` allowing any additional properties, and `object()` forbidding them, that would be a BC break. `object(false,propName:propType)` could be a backward-compatible way to define 'strict' objects.

Alternatively, the syntax could be (here I use ellipsis literally, e.g. it will appear in annotations) `object(...)` allowing any properties (equivalent to current `object()`), `object(...type)` allowing properties matching the type constraints and `object(...!)` (or `object(!...)`) disallowing additional properties.

**Comment by weirdan** [comment]
Here's the current test for the syntax with ellipsis:
```
model IdModel object(id:uuid)

model AnyPropertiesAllowed object(...)

model AnyPropertiesAllowedCommand object
additionalproperties true

model TypedPropertiesAllowedInline object(...integer)

model TypedPropertiesAllowedCommand object
additionalproperties integer

model RefPropertiesAllowedInline object(...IdModel)

model RefPropertiesAllowedCommand object
additionalproperties IdModel

model NoAdditionalPropertiesAllowedInline object(propName:integer,...!)

model NoAdditionalPropertiesAllowedCommand object
property integer propName
additionalproperties false

model MixedPropertiesAndAdditionalPropertiesInline object(propName:integer,...)

model MixedPropertiesAndAdditionalPropertiesCommand object
property integer propName
additionalproperties true

model MixedPropertiesAndTypedAdditionalPropertiesInline object(propName:integer,...string)

model MixedPropertiesAndTypedAdditionalPropertiesCommand object
property integer propName
additionalproperties string

model MixedPropertiesAndRefAdditionaPropertiesInline object(propName:integer,...IdModel)

model MixedPropertiesAndRefAdditionalPropertiesCommand object
property integer propName
additionalproperties IdModel
```
Item starting with '...' would only be allowed once per prop-list, `additionalproperties` command would only be allowed once for definition and would be disallowed if the item starting with '...' was seen during parsing of the inline definition.
