### ISSUE TITLE
Associative arrays are cast to objects, not arrays

### ISSUE THREAD

**Issue by ObliviousHarmony** [vanderlee/PHPSwaggerGen#4]
As per the documentation (http://php.net/manual/en/function.json-encode.php), all associative arrays are turned into JSON objects. In some cases this violates the Swagger spec, such as with security options on routes, where it expects an array. This behaviour also seems to happen in the YAML output, so perhaps this is consistent in PHP's built in functions.

**Comment by vanderlee** [comment]
I think this is already fixed in the new 2.3.1. Please check.

Casting assoc arrays to objects is correct, as JSON (or YAML) supports no other method to handle assoc arrays. The problem was in a missing intermediate non-assoc array.

**Comment by ObliviousHarmony** [comment]
Ah, I see.

I've tested the latest release and all compliance issues have been resolved. Good work!
