### ISSUE TITLE
PHP Parser fails when parsing @rest\property!

### ISSUE THREAD

**Issue by SteenSchutt** [vanderlee/PHPSwaggerGen#44]
The regex on this line:
https://github.com/vanderlee/PHPSwaggerGen/blob/752f0e44625b4f55d3228815453f62e679d035c7/SwaggerGen/Parser/Php/Parser.php#L159

Should be changed to: `'~^@' . preg_quote(self::COMMENT_TAG) . '\\\\([a-z][-a-z]*[?!]?)\\s*(.*)$~'`

It fails when attempting to parse the following:
```
/**
 * @rest\definition Account
 * @rest\property! int[0,] id
 */
```

The resulting matches array looks like this:
```
Array
(
    [0] => @rest\property! int[0,] id
    [1] => property
    [2] => ! int[0,] id
)
```

It is expected to look like this:
```
Array
(
    [0] => @rest\property! int[0,] id
    [1] => property!
    [2] => int[0,] id
)
```

I am not particularly good with PHPUnit, so feel free to create a test for this case.

**Comment by vanderlee** [comment]
Fixed through your own pull request. Will bump version soon
