### ISSUE TITLE
PHP 8 error: array and string offset access with curly braces

### ISSUE THREAD

**Issue by daniol** [vanderlee/PHPSwaggerGen#46]
The library is not compatible with PHP 8.0 due two syntax errors.

> Fatal error: Array and string offset access syntax with curly braces is no longer supported in SwaggerGen\Swagger\Type\AbstractType.php on line 96

> Fatal error:  Array and string offset access syntax with curly braces is no longer supported in SwaggerGen\Swagger\Swagger.php on line 236

**Comment by daniol** [comment]
See: https://wiki.php.net/rfc/deprecate_curly_braces_array_access

**Comment by vanderlee** [comment]
Thanks for the fix!
